version: "3.4"

services:
  ib-gateway:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: ${TRADING_MODE}
      VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD}
    ports:
      - "4001:4001"
      - "4002:4002"
      - "5900:5900"
      - "7462:7462"
